spring.application.name=jobportal
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal
spring.datasource.username=jobuser
spring.datasource.password=job123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true